### ISSUE TITLE
setup general train/test pipeline

### ISSUE THREAD

**Issue by damniko** [KasperHenningsen/P6-Project#19]
vi skal let kunne skifte mellem hvilken model vi kører (og med hvilke parametre), måske med program arguments eller lignende

**Comment by mirakst** [comment]
synes ikke det her skal prioriteres vildt højt, det er allerede meget let (dog ikke elegant), men vi kan godt hvis du har en god idé

**Comment by mirakst** [comment]
lige nu har jeg bare alle modeller defineret, og så 'peger' jeg på én af dem med en variabel (training_model), som så bliver trænet og plottet. så skal man kun ændre på hvilken model training_model peger på, og alle parametrene kan justeres i definitionerne

![Image](https://user-images.githubusercontent.com/74593818/230601056-92e5579c-5609-452f-8c26-1dfbb4289161.png)
